Make certdata2pem.py work with newer cryptography versions
certdata2pem.py is incompatible the cryptography package version 2.

    $ pip3 install -U cryptography~=2.0  # 2.9.2
    ...

    $ python3 certdata2pem.py
    ...
    Traceback (most recent call last):
      File "certdata2pem.py", line 125, in <module>
        cert = x509.load_der_x509_certificate(obj['CKA_VALUE'])
    TypeError: load_der_x509_certificate() missing 1 required positional argument: 'backend'

    $ pip3 install -U cryptography~=3.0  # 3.4.8
    ...

    $ python3 certdata2pem.py  # ok
    ...

I think this should be noted in README.

cryptography>=35.0 is also incompatible:

    $ pip3 install -U cryptography~=35.0
    ...

    $ python3 certdata2pem.py
    Traceback (most recent call last):
      File "certdata2pem.py", line 125, in <module>
        cert = x509.load_der_x509_certificate(obj['CKA_VALUE'])
      File "/home/wsh/.local/lib/python3.8/site-packages/cryptography/x509/base.py", line 443, in load_der_x509_certificate
        return rust_x509.load_der_x509_certificate(data)
    TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyBytes'